### ISSUE TITLE
Default value of phpthumbsup.base_url

### ISSUE THREAD

**Issue by ghost** [darkstardigital/phpThumbsUp#10]
Would it make sense to change the default value of phpthumbsup.base_url from
**phpthumbsup/** 
to
**/phpthumbsup/** 

This could prevent path confusions, especially for new users.

**Comment by patrickmckay** [comment]
Well it depends on the user's installation of MODX. If MODX is installed in the sites root directory then yes, it would make sense. However, some people install modx to a subdirectory, such as www.mydomain.com/modx. In this case, the thumbsup url is actually /modx/phpthumbsup. By leaving the slash off the front, the base url is relative to the MODX url instead of the site root.

**Comment by sdwespi** [comment]
Actually there's another issue with an even better idea:

https://github.com/darkstardesign/phpThumbsUp/issues/2

Using the actual {base_url} setting would be better for multiple contexts - that would probably be the best way to handle it.
