### ISSUE TITLE
Workinmg fine on live site and MODX Cloud, not working on localhost.

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [darkstardigital/phpThumbsUp#11]
Did you guys got this working on WAMP?

**Comment by sdwespi** [comment]
Honestly we don't have a good testing environment for WAMP in the office, so we're not sure. Are you getting anything in the error log? Do other image processing packages like phpThumbOf work?

In the future we might be able to scrounge together a WAMP machine to test with, but if you could help us debug it for now that would be great!

**Comment by billschmidt** [comment]
Besides the Apache error log, you might run a phpinfo(); to check your environment has PHP 5.3.x and ImageMagick 6.x or the GD Library.

**Comment by sdwespi** [comment]
Someone shed some more light on the Windows issues here: http://forums.modx.com/thread/85893/new-version-of-phpthumbsup-supports-responsive-images#dis-post-474170

I'm guessing it's an issue with filemtime but we'll look into it.

**Comment by patrickmckay** [comment]
After reading jellefaber's post on the MODX forums I suspect the issue lies in how we are handling file paths. PHP usually translates Linux paths to Windows paths automatically. However, I wonder if for some reason filemtime() is not translating the path. I glanced at the code in phpthumbsup.class.php and we hard code the slash "/" when building file paths instead of using the DIRECTORY_SEPARATOR constant.

The same error that jellefaber describes where the image is generated but nothing displays also occurred when debugging some issues for the 1.0.1 release, and it was related to incorrect paths (I believe the exact issue in that case was a missing slash).

**Comment by FountainInternet** [comment]
The problem seems to be in line 422 of phpthumbsup.class.php. The %T format parameter is not supported in Windows, so to fix the problem change this line:

```
$last_modified = gmstrftime('%a, %d %b %Y %T %Z', filemtime($file));
```

to:

```
$last_modified = gmstrftime('%a, %d %b %Y %H:%M:%S %Z', filemtime($file));
```

It's explained [here](http://www.php.net/manual/en/function.strftime.php): "%e, %T, %R and, %D (and possibly others) - as well as dates prior to Jan 1, 1970 - will not work on Windows, some Linux distributions, and a few other operating systems".

**Comment by sdwespi** [comment]
Thanks for the info, FountainInternet. We'll switch away from the %T parameter in the next release.

-Scott
